services:
  - type: web
    name: botpress
    runtime: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: BP_HOST
        value: 0.0.0.0
      - key: BP_PORT
        value: $PORT
